services:
  couchdb:
    container_name: couchdb-a
    image: apache/couchdb:latest
    restart: unless-stopped
    ports:
      # HOSTPORT : CONTAINERPORT
      - "5984:5984"
    volumes:
      - couchdata:/opt/couchdb/data
    networks:
      - backend
    environment:
      # cluster_nodes: node@host  => {"all_nodes":["couchdb@sun"], ...
      - NODENAME=alpha
      - COUCHDB_USER=christian
      - COUCHDB_PASSWORD=pw

volumes:
  couchdata: {}

networks:
  backend: {}